### ISSUE TITLE
some suggestion for tadpole stake feature

### ISSUE THREAD

**Issue by WacthThis** [Tadpole-finance/tadpole-finance.github.io#16]
**sorry, i put here cause i can't code**

**1.** show APY at staking page (https://tadpole.finance/staking.html)
**2.** show total stake include people who stake with power on
**3.** add button for direct to swap tad:eth pair at uniswap 
https://app.uniswap.org/#/swap?inputCurrency=0x9f7229af0c4b9740e207ea283b9094983f78ba04
**4.** add button for direct to add liquidity tad:eth at uniswap https://app.uniswap.org/#/add/0x9f7229af0c4b9740e207ea283b9094983f78ba04/ETH
**5.** disable function stack for 360 days if stacking already run for 60 days from day one 
**6.** disable function stack for 180 days if stacking already run for 240 days from day one
**7.** disable function stack for 90 days if stacking already run for 330 days from day one
**8.** put warning when people want to stacking with locking period  

0x91ffb2585f84247e50a27df4866ab054f55b5d21

**Comment by ngkong** [comment]
most issues have been addressed. suggestion 5-7 are very good ideas, we will implement this
