### ISSUE TITLE
Explanation on developer rewards

### ISSUE THREAD

**Issue by mfnoviar** [Tadpole-finance/tadpole-finance.github.io#17]
The explanation of the distribution and the distribution of tokens is very well explained on the FAQ page.
Genesis Mining: 200,000 (20%) (30 days period)
Platform Liquidity Mining: 500,000 (50%) (2 year period)
DEX Liquidity Mining: 200,000 (20%) (1 year period)
Developer Rewards: 100,000 (10%) (1 year period)

But where does the TAD token rewards go if in 1 year period there is a month or a certain period of time let's say that none of (developer) has made a pull request or development of tadpole finance?

Why this become so important? As we all know the blockchain industry prioritizing transparency especially on DeFi projects, thus should be added and explained in faq (developer rewards program section). This also can be an incentive / motivation for any developer to continue developing every month for the next 1 year.

**Comment by mfnoviar** [comment]
0x55047F2C4184f8Ea6AC2e57162daf78d18603Bda

**Comment by ngkong** [comment]
i will make sure at there will be at least 1 PR in a month :smile:
