### ISSUE TITLE
Add Label to Github Issues/Pull Requests

### ISSUE THREAD

**Issue by syadluq** [Tadpole-finance/tadpole-finance.github.io#19]
Refers to FAQ Page, Developer Rewards Program Section, anyone act As Developer, Submitting Issues and/or Pulling Requests get Tagged by "Score"

 The distribution of rewards will be measured based on a score that represents the level of difficulty and the significance of your contribution to the Tadpole Finance ecosystem. Score is defined as follows:

score: very-low (1)
score: low (2)
score: medium-low (3)
score: medium (5)
score: medium-high (8)
score: high (13)
score: very-high (21)
score: critical (34)
*) the numbers are calculated based on fibonacci if you are curious.

The core developers will determine a score for each incoming pull request by assigning a label to it. The score is subjective and final.

For example, user1 made a pull request "Fix typo in documentation, TOD to TAD" and this is labeled as “score:very-low(1)”.

**Comment by syadluq** [comment]
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/72981964/99183460-7f444b00-276e-11eb-97d2-1296749730e2.PNG">
Currently, Only Default Github Label Available (9 Labels)

**Comment by ngkong** [comment]
it's there now
