### ISSUE TITLE
Update Name Wallet for Dex Liquidity Mining

### ISSUE THREAD

**Issue by Neetsuki** [Tadpole-finance/tadpole-finance.github.io#24]
Please update name wallet for dex liquidity mining in etherscan.
Change name wallet "[0x0c14e822e43796d955a30b6d974f62031da845e3](https://etherscan.io/token/0x9f7229aF0c4b9740e207Ea283b9094983f78ba04?a=0x0c14e822e43796d955a30b6d974f62031da845e3)" to "Tadpole Finance : Dex Liquidity Mining"

Like wallet "[0x8cb331d8f117a5c914fd0f2579321572a27bf191](https://etherscan.io/token/0x9f7229aF0c4b9740e207Ea283b9094983f78ba04?a=0x8cb331d8f117a5c914fd0f2579321572a27bf191)" change name to "Tadpole Finance: Genesis Mining".

This thing makes it easier for users to find out which wallet are used to share dex liquidity mining result.
Thanks...

**Comment by ngkong** [comment]
great suggestion

**Comment by ngkong** [comment]
a new label is submitted to etherscan

**Comment by ngkong** [comment]
solved
