### ISSUE TITLE
Add Other Market Menu Available for Buy and Sell Tad on the FAQ

### ISSUE THREAD

**Issue by Neetsuki** [Tadpole-finance/tadpole-finance.github.io#25]
Please add other market menu that available for buying and selling tad in the Tadpole Finance FAQ.

Like...
Uniswap : [http://uniswap.tadpole.finance](http://uniswap.tadpole.finance) or [https://info.uniswap.org/token/0x9f7229af0c4b9740e207ea283b9094983f78ba04](https://info.uniswap.org/token/0x9f7229af0c4b9740e207ea283b9094983f78ba04)
Bithumb (coming soon) : [https://www.bithumb.pro/en-us/exchange/professional?q=TAD-USDT](https://www.bithumb.pro/en-us/exchange/professional?q=TAD-USDT)
And of course Indodax and Tokenomy will be sure to do it too, because this is their defi project so they will definitely list it there, just a matter of time.

Because if it not added, people who don't join telegram, those who don't know for for buy or selling tad, there are ready too in other market like uniswap, bithumb etc...
Thank you...

**Comment by ngkong** [comment]
uniswap menu added on #47
other exchanges information will be described in the documentation (upcoming)
