### ISSUE TITLE
stake apy calculator still not accurate

### ISSUE THREAD

**Issue by WacthThis** [Tadpole-finance/tadpole-finance.github.io#34]
Formula: {TAD price} * {stake reward} / ( {ETH reserve} * {ETH price} + {TAD reserve} * {TAD price} } * {LP Supply} / {Staked LP} * multiplier

{LP Supply} should be {LP Supply include power}

which is we are still dont know the exact number

**Comment by WacthThis** [comment]
thank for showing total stake power, now just change lil bit on the formula

**Comment by ngkong** [comment]
it should be accurate now
