### ISSUE TITLE
tadpole icon hasn't changed

### ISSUE THREAD

**Issue by himmura** [Tadpole-finance/tadpole-finance.github.io#35]
tadpole logo hasn't changed,
still the past tadpole, in metamask or trust wallet.
would create confusion, because in coingecko
use new logo tadpole.

Thank you

![Screenshot_2020-11-30-23-00-45-84](https://user-images.githubusercontent.com/74728414/100632888-f3cadc80-335f-11eb-8549-e0abaefbd325.jpg)

**Comment by ngkong** [comment]
in metamask, unfortunately we can't do much about it because the data is stored locally.
the logo in trustwallet should be updated, can you confirm?

**Comment by ngkong** [comment]
closed due to inactivity
