### ISSUE TITLE
if there is a whitepaper it is very quite good

### ISSUE THREAD

**Issue by himmura** [Tadpole-finance/tadpole-finance.github.io#36]
I not find whitepaper about Tadpole.Finance
if there is a whitepaper it is very good,
people can read it, and feel the thoughts of the tadpole project so that it makes reading interested to explore this project.

if it could exist whitepaper, why not, it would be very useful for people to understand your way of thinking

If you want to send me TAD Reward, this is my TAD Wallet :
0xF2f71c4dB7E1E490d53e2fa6a681A03d372a9F17

Thank you,

**Comment by ngkong** [comment]
thank you for the suggestion
