### ISSUE TITLE
about APY Tadpole Finance simple calculations

### ISSUE THREAD

**Issue by himmura** [Tadpole-finance/tadpole-finance.github.io#37]
I wanna little interuption

My calculation is simple in tadpole finance staking, at 1000 $ I get 7LP in the current condition (4716 LP ) with 360day contract,
I can get 1TAD per day, so
1TAD x360hr = 360TAD x 6 $ = 2160 $ ​​which means, the APY = around 200% (with fixed conditions)
maybe it can be explained, in order to help the community

Thank you

**Comment by ngkong** [comment]
your calculation is consistent with the apy calculator, which is currently around 200%
