### ISSUE TITLE
TAD Developer Program

### ISSUE THREAD

**Issue by syadluq** [Tadpole-finance/tadpole-finance.github.io#38]
As written on FAQ Page since October 2020, It says started November 2020, mean 1st - 30th November
But now 8th December and no reward received, yet.

I created few Issues and Pull Requests, and some changes have been made to the core repository

0x16DfCeabb08A4f0DEffc28B8d7beA29EE120cab7

**Comment by ngkong** [comment]
it's delayed to december, sorry for the issue
