### ISSUE TITLE
Please Change Style Cursor "Hand" Only in Button Action or Hyperlink

### ISSUE THREAD

**Issue by prayogih** [Tadpole-finance/tadpole-finance.github.io#43]
please change Style cursor **"Hand"** only in the top Button or Hyperlink. In tadpole.finance not only above them, but it looks bad because it's not above the action button or hyperlink. 
if this is issu, big thank : 0xE04E0Fec2D4b37bF5860ACbEbA99B72FC2975a04

https://user-images.githubusercontent.com/74474384/102683962-2d786000-4207-11eb-83d0-3c495d256061.mp4
such as in video above.

**Comment by ngkong** [comment]
dont create multiple PR for same issue
