### ISSUE TITLE
soft reminder - old logo thumbnail doesn't change to a new one

### ISSUE THREAD

**Issue by KaptenAkro** [Tadpole-finance/tadpole-finance.github.io#59]
![IMG_20201223_182824](https://user-images.githubusercontent.com/73269185/102988616-21660880-454f-11eb-92de-16ba6a58ee13.jpg)
![Logo-Tadpole-128x128px](https://user-images.githubusercontent.com/73269185/102988636-27f48000-454f-11eb-80a8-dabecde18fa5.png)

The supposed to be a new thumbnail logo doesn't appear on search engine as image attached.

**Comment by ngkong** [comment]
it's updated from my end
