### ISSUE TITLE
Dev Reward Program

### ISSUE THREAD

**Issue by KaptenAkro** [Tadpole-finance/tadpole-finance.github.io#67]
In continuation of my previous question ; What happen to the unclaimed reward from the previous month? Would it be accumulated into the following event? e.g. as of December 2020 the total claimed reward is 7000 TAD, and the remaining unclaimed reward is 1333 TAD - Where do these token go?
And What if the bounty reward should be distributed exceeding Dev's monthly supply like 10K TAD, meanwhile the monthly quota is 8333 TAD ?
I believe there's should be additional information regarding this term.
My suggestion are:
1. The unclaimed reward will be accumulated into the following month event.
2. The exceeding claimable token will be distributed from the following month quota's.
3. Program is based on first come first served basis.
4. Should there be any changes on term and conditions of this program will be solely on Developer's discretion.

Or Developer can release their own version of wording to explain the additional conditions.

**Comment by ngkong** [comment]
monthly rewards is 8333 TAD and will be distributed prorated
